// <auto-generated />
using System;
using MandagsSpil.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MandagsSpil.Api.Migrations.Persistence
{
    [DbContext(typeof(PersistenceContext))]
    [Migration("20250905093849_AddUserCod2UsernameIndex")]
    partial class AddUserCod2UsernameIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MandagsSpil.Api.Models.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("GameId"));

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsTie")
                        .HasColumnType("boolean");

                    b.Property<string>("MapName")
                        .HasColumnType("text");

                    b.Property<string>("WinningTeam")
                        .HasColumnType("text");

                    b.HasKey("GameId");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("MandagsSpil.Api.Models.PlayerResult", b =>
                {
                    b.Property<long>("PlayerResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PlayerResultId"));

                    b.Property<string>("Cod2Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Deaths")
                        .HasColumnType("integer");

                    b.Property<long>("GameId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ping")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerResultId");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("PlayerResults", (string)null);
                });

            modelBuilder.Entity("MandagsSpil.Api.Models.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserId"));

                    b.Property<string>("Cod2Username")
                        .HasColumnType("text");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("Cod2Username");

                    b.HasIndex("IdentityId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MandagsSpil.Api.Models.PlayerResult", b =>
                {
                    b.HasOne("MandagsSpil.Api.Models.Game", "Game")
                        .WithMany("PlayerResults")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MandagsSpil.Api.Models.User", "User")
                        .WithMany("PlayerResults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MandagsSpil.Api.Models.Game", b =>
                {
                    b.Navigation("PlayerResults");
                });

            modelBuilder.Entity("MandagsSpil.Api.Models.User", b =>
                {
                    b.Navigation("PlayerResults");
                });
#pragma warning restore 612, 618
        }
    }
}
